# This workflow will do a clean install of node dependencies,
# run tests across different versions of node with coverage reports,
# and emit the report to Coveralls.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      # only lint on current LTS version
    - if: ${{ matrix.node-version == '16.x' }}
      run: npm run strictCheck
    - run: npm run cover
      # use LTS version to report to coveralls
    - name: Coveralls
      uses: coverallsapp/github-action@master
      if: ${{ matrix.node-version == '16.x' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
